app/components/sections/discord-section.tsx

Fixes the speech bubble as shown in: https://github.com/kentcdodds/remix-kentcdodds/pull/13#issuecomment-869834796

fix: force vertical alignment of discord speech bubbles

---

app/routes/blog/index.tsx

fix: support filtering on tags containing spaces

---

app/components/arrow-button.tsx
app/components/button.tsx
app/components/sections/hero-section.tsx
app/components/workshop-card.tsx
app/routes/workshops/$slug.tsx
app/routes/workshops/index.tsx
styles/tailwind.css
tailwind.config.js

polish the workshops detail page

feat: implement workshop detail page

---

app/routes/me.tsx

Improved the QR code transition & hidden state:
https://user-images.githubusercontent.com/1196524/125661399-afe6179c-fed6-4323-9ab8-6ba0d92db733.mp4

feat: improve `reveal QR code` button

---

app/components/errors.tsx
app/components/sections/hero-section.tsx
app/routes/$slug.tsx
app/routes/404.tsx
app/routes/blog/$slug.tsx
app/routes/index.tsx
app/routes/workshops/$slug.tsx
app/utils/mdx.tsx

Added a server error page that can be rendered from the ErrorBoundary. A simple copy of the 404, but with different captions.

feat: add 500 page

---

app/components/button.tsx
app/components/course-card.tsx

https://user-images.githubusercontent.com/1196524/125960607-43a931fb-9cca-4db6-8203-b8c67f1aa6be.mp4

feat: animate arrow on course card buttons

---

app/external-links.tsx
app/routes/blog/$slug.tsx
content/blog/application-state-management-with-react.mdx
content/blog/how-to-use-react-context-effectively.mdx
content/blog/inversion-of-control.mdx
content/blog/state-colocation-will-make-your-react-app-faster/index.mdx

An attempt to fix #60.
I've also tried adding the up-right arrow to the pills, but with multiple translations that gets quite crowded.
https://user-images.githubusercontent.com/1196524/126079729-94644abd-1de1-43f5-97d1-23d7e3cbdc64.mp4

feat: make translations look less bad

---

app/components/icons/chevron-up-icon.tsx
app/components/icons/triangle-icon.tsx
app/routes/chats/$season.tsx

- Added the play icon on hover (as per design)
- Made chevron-up point up
https://user-images.githubusercontent.com/1196524/126162672-0c53c1bb-1b9c-49e4-8b67-d7ce10e4afb0.mp4

feat: add play icon on top of thumbnail during hover

---

app/components/navbar.tsx
app/components/team-stats.tsx
app/images.tsx
app/routes/blog/$slug.tsx

I've added the team stats to the blog pages. 
https://user-images.githubusercontent.com/1196524/126185154-116d182e-f393-4d1b-8c6c-1bb2378d1180.mp4

feat: add team read count to blog

---

app/components/button.tsx
app/components/call/recorder.tsx
app/components/call/submit-recording-form.tsx
app/components/form-elements.tsx
app/components/icons/microphone-icon.tsx
app/components/icons/pause-icon.tsx
app/components/icons/square-icon.tsx
app/routes/call.record.tsx
app/routes/call.record/$callId.tsx

Added "all the" call recorder pages. They ain't awesome. But it's a start.

feat: make call recorder look less terrible

---

app/components/form-elements.tsx
app/components/sections/hero-section.tsx
app/routes/contact.tsx

Made the contact form look pretty.

feat: implement contact page

---

app/components/arrow-button.tsx
app/components/article-card.tsx
app/components/footer.tsx
app/components/navbar.tsx
app/components/sections/about-section.tsx
app/components/sections/discord-section.tsx
app/components/sections/header-section.tsx
app/components/sections/introduction-section.tsx
app/components/sections/problem-solution-section.tsx
app/components/typography.tsx
app/external-links.tsx
app/routes/index.tsx
styles/app.css
styles/tailwind.css

All kinds of visual improvements:
- added underlines to links in navbar (animated from left to right, (progress-bar?))
- improved hover state on navbar links
- changed hover state of dark/light toggle and user menu
- added animations to the "problem/solution" section on the home page
- improved footer, added capitalization and fixed colors for light theme
- improved contrast of various texts in light theme
- added "progress animation" to the arrow button/link
- improved various spacings on elements at the home page

various visual improvements around home page

---

.dockerignore
.github/workflows/pipeline.yml
Dockerfile
fly.toml

This fixes the previous docker build issues, builds + pushes the image in one step, and then deploys the image separately. It's a pretty nice speedup!

Docker deploy (round 2)

---

app/routes/blog/$slug.tsx

I think changing the color on hover makes it look better:
https://user-images.githubusercontent.com/1196524/126910112-6904fabc-639c-493a-b67d-16d681ccd2e5.mp4

feat: change `add translation` link color on hover

---

app/components/arrow-button.tsx
app/components/hooks/use-element-state.tsx

feat: add animated focus state to arrow links

---

app/components/navbar.tsx
app/root.tsx
app/utils/theme-provider.tsx

https://user-images.githubusercontent.com/1196524/127339565-8641be1e-9e4a-497d-846e-3d1e41befd49.mp4

feat: animate theme toggle

---

app/routes/discord.tsx
styles/tailwind.css

https://user-images.githubusercontent.com/1196524/127473048-b08f5b85-383a-4b94-aa4c-7510e436eedc.mp4

feat: upgrade discord feature table hover & focus styles

---

app/components/notification-message.tsx
app/components/sections/hero-section.tsx
app/root.tsx
package-lock.json
package.json
styles/app.css

I took the liberty to add some animation to the hero. Please feel free to close it if you don't like what you're seeing. 
It's a bit slow on when remix is building the cache, but I assume that the user will practically never be in that state.

feat: add motion to the hero

---

app/components/sections/course-section.tsx
app/routes/courses/index.tsx

Fixes the external linking to the Testing JavaScript course.

Fix testing javascript course link

---

content/data/credits.yml

This adds data to the `credits.yml` file. I'm attaching the profile images here for uploading to cloudinary:
Cree
Haze
Kevin
Maggie

Add credits data
