- tailwind.config.js
This change prevents tailwind (postcss) from purging css in development mode. Making things faster, and reduce the need for full server restarts.
> feat: don't purge tailwind in development mode

- storybook/.storybook/main.js
- storybook/.storybook/preview.js
- storybook/.storybook/storybook.css
- storybook/package-lock.json
- storybook/package.json
Added `storybook-dark-mode`, so we can switch between light and dark mode in storybook.
It defaults to `dark` and applies the `dark` class to the `body` inside the iframe. I use the `storybook.css` file to control the frame's background color. These values should be adjusted to match the real theme when the style guide/color scheme comes in.
Preview:
> feat: add dark-mode switch to storybook

- storybook/pm2.config.js
Added the `-s` flag to storybook, so that all static files from `/public` are available to it. This helps serving local images for example.
https://storybook.js.org/docs/riot/configure/images-and-assets#serving-static-files-via-storybook
Worth considering, I've only specified the `/public` folder, but we could also add a second folder like `/storybook/fixtures`. This folder could then be used for custom placeholder images that shouldn't be included on production servers.
> feat: serve static files via storybook

- app/components/course-card.tsx
- app/components/pages/home.tsx
- app/components/sections/hero-section.tsx
- app/components/sections/problem-solution-section.tsx
- app/root.tsx
- changed hero to match screen height, without the navbar+hero wrapper.
- fixed the `course-card` to have a background on light mode
- fixed the `@reach/tabs` to have correct styles when `@reach/tabs/style.css` is imported, by changing the app.css and tailwind.css load order
- fixed page background color for light/dark modes
> fix: polish home page

- app/components/footer.tsx
- app/components/grid.tsx
- app/components/sections/blog-section.tsx
- app/components/sections/course-section.tsx
- app/components/sections/problem-solution-section.tsx
- app/components/tag.tsx
- app/components/typography.tsx
- app/routes/blog/$slug.tsx
- app/routes/blog/index.tsx
- app/routes/index.tsx
- app/utils/mdx.tsx
- storybook/stories/sections.stories.tsx
- tailwind.config.js
I've added some typography (prose) styles to `tailwind.config.js` so we control blog styles through prose. This felt better than providing custom components to the mdx parser. Prose for blogs, utility classes for everything else.
I've also fixed a small typo in the `KCDMdxComponent.components` prop, and I've removed the row-gap from the grid component. The column-gap works great, but the row-gap was only standing in the way.
I'm not done yet. I need to add a few more element types, and I'm chatting with the designer about some details. So
<p align="center">
to be continued
</p>
> feat: add blog detail page

- app/routes/blog/index.tsx
Hide the `Search blog by topics` caption when there are no topic buttons to click on, and move around some spacing to make everything right.
> small improvements for blog index page

- styles/prose.css
- tailwind.config.js
Improved the highlighted code blocks:
- code blocks now span full screen width on narrow screens (`< screen:lg`)
- highlighted lines are now extended to the full frame width, also when horizontally overflown
- line numbers are now sticky, so that they'll remain visible when scrolling horizontally
> various optimizations to code blocks

- app/components/button.tsx
- app/components/form-elements.tsx
- app/components/tag.tsx
- app/routes/signup.tsx
- app/routes/workshops/index.tsx
- package-lock.json
- package.json
- styles/app.css
- styles/tailwind.css
- tailwind.config.js
Polished the `/workshops` page
I've also added the `focus-ring` css utility and applied it to a few existing places. This utility replaces various hover & focus utilities with a single className. I'll probably do this with a few more things over the next few PR's, as abstractions will become clearer.
> feat: implement workshops page

- app/components/form-elements.tsx
- app/components/icons/logout-icon.tsx
- app/routes/me.tsx
- app/routes/signup.tsx
- app/utils/onboarding.ts
- cypress/e2e/discord.ts
I've added some colors and content to the profile page, but I'm waiting for response from Gil for the QR code implementation.
> feat: implement profile page

- app/components/article-card.tsx
- app/components/course-card.tsx
- app/components/footer.tsx
- app/components/numbered-panel.tsx
- app/components/sections/featured-section.tsx
- app/components/sections/hero-section.tsx
- app/components/sections/testimonial-section.tsx
- app/components/video-card.tsx
- app/components/workshop-card.tsx
- app/routes/about.tsx
- app/routes/blog/$slug.tsx
- app/routes/blog/index.tsx
- app/routes/chats.$season.$episode.$slug.tsx
- app/routes/chats.tsx
- app/routes/chats/$season.tsx
- app/routes/courses/index.tsx
- app/routes/discord.tsx
- app/routes/me.tsx
- app/routes/signup.tsx
- app/routes/workshops/index.tsx
Removed level skipping in headings, and removed some headings altogether. I've also added headings visible to screen-readers only above the guest listing on the podcast pages, and above the courses on the courses page.
> fix: resolve all heading order violations

- app/components/footer.tsx
Pointed the footer links to existing pages where possible. I also added `credits`, and noticed that `Discord` is listed twice.
> fix: update footer links

- app/routes/chats.$season.$episode.$slug.tsx
Fixed the alignment of the prev/next buttons below the podcast player on mobile screens, and the squashing of the images in them.
> fix: squishing of podcast prev/next buttons

- app/components/errors.tsx
- package-lock.json
- package.json
Improved the 500-error page by showing the error when in development mode. It's dismissable by clicking on the backdrop. 
I haven't tested, but due to the check on `NODE_ENV` it shouldn't appear in production mode.
https://user-images.githubusercontent.com/1196524/125967843-8e9e01d2-6670-4fc4-a995-0676defa4854.mp4
> feat: add redbox for server errors in dev env

- tailwind.config.js
fixes #64 
Maybe we should also limit the max-width of the navbar to stay closer to the content width? A bit wider as content, but not as wide as shown in #64?
> fix: limit height of hero for ultra-high screens

- app/components/article-card.tsx
- app/components/clipboard-copy-button.tsx
- app/components/icons/check-circled-icon.tsx
- app/components/icons/check-icon.tsx
- app/components/icons/copy-icon.tsx
- app/components/sections/featured-section.tsx
- app/routes/404.tsx
- app/routes/blog/index.tsx
- app/routes/chats.$season.$episode.$slug.tsx
- app/routes/me.tsx
- app/routes/signup.tsx
Improved the copy-button:
- added copy functionality
- added a "copy confirmation" state
- moved the button on the featured section inside the photo (match the gallery cards)
- removed the copy button from all other feature sections
**TODO:**
- set article urls to be copied (blocked by #53 / decision making)
**PREVIEW:**
https://user-images.githubusercontent.com/1196524/125971669-1256f429-518e-4d6c-a41c-874a18d0c8f8.mp4
> feat: improve copy button

- app/components/team-stats.tsx
- app/routes/blog/$slug.tsx
- increased the size difference between bars
- rendered them horizontally
- fixed to top and bottom of the article, instead of sticky on screen
- added user avatar in case they're logged in
https://user-images.githubusercontent.com/1196524/126388598-facfe787-e064-44df-a2ed-6bd24023c1d5.mp4
> feat: render team-charts horizontally and fixed at top/bottom of article

- app/routes/discord.tsx
Not sure what happened. It should have been there, but according to git log, it never existed.
Anyways, (re)added the join button to the discord hero:
> feat: add join button to hero on discord page

- app/routes/$slug.tsx
- content/pages/about.mdx
- content/pages/appearances.mdx
- content/pages/clubs.mdx
- content/pages/links.mdx
- content/pages/transparency.mdx
I've applied the same header/image/content logic to the content pages, as we do for blog articles. This results in pretty rendering for:
- /appearances
- /clubs
- /conduct
- /info
- /links
- /transparency
I think the pages would benefit immensely if we'd added some banner images to them.
> feat: render content/pages using prose classes

- app/routes/call.tsx
- app/routes/call/$slug.tsx
- app/routes/chats.tsx
- app/routes/index.tsx
- app/utils/blog.server.ts
- mocks/transistor.ts
Added color and content to the `/call` page. The design is inspired by `/chats` (podcast), but instead of opening every call in a details page, they expand and show the player inline.
**TODOS**
- Alex is rendered, but in low quality. We need higher resolution images
**IDEAS**
_copied from Discord:_
- Add search (like on blog page)
- Add keyword filter (like on blog page)
- Display summary on each row, and the description in expanded view?
- Display the keywords on each row as well?
> feat: implement call page

- app/components/button.tsx
Add support for external links to the `ButtonLink`, which is used by the `CourseCard`. Without this, the destination url becomes `https://kent.dev/https://testingjavascript.com`.
> fix: use native anchors for external links

- app/components/button.tsx
- app/components/call/recorder.tsx
- app/components/call/submit-recording-form.tsx
- app/components/clipboard-copy-button.tsx
- app/components/form-elements.tsx
- app/components/navbar.tsx
- app/components/sections/about-section.tsx
- app/components/sections/blog-section.tsx
- app/components/sections/discord-section.tsx
- app/components/sections/header-section.tsx
- app/components/sections/introduction-section.tsx
- app/components/sections/problem-solution-section.tsx
- app/components/sections/testimonial-section.tsx
- app/routes/blog/$slug.tsx
- app/routes/blog/index.tsx
- app/routes/call.record.tsx
- app/routes/chats.$season.$episode.$slug.tsx
- app/routes/chats.tsx
- app/routes/courses/index.tsx
- app/routes/discord.tsx
- app/routes/index.tsx
- app/routes/me.tsx
- app/routes/signup.tsx
- app/routes/talks.tsx
- app/routes/workshops/index.tsx
- styles/app.css
A whole lot of various improvements, small, and some a little bigger.
**fixes**
- Some arrow links that didn't point to a page, now do.
- Restored the episode number in the podcast prev/next buttons.
- Couple of spacing issues on various pages.
- Restore missing arrow buttons in the recommended articles section.
**improvements**
- Improved `/blog` page
- The gallery didn't render full rows on large screens. I've adjusted the page size, so that the pages are divisible by both 2 and 3 (medium and large screens).
- Added hover styles to search input
- Various improvements in colors & hover styles.
- The `team-unknown` color now depends on the theme.
- Improved hover style of mobile menu
- Added hover style to tabs in problem-solution section
- Improved background color of input elements …
> fix: various visual improvements across the whole site

- app/routes/blog/index.tsx
Or well, at least partially. When the user is only using the filter buttons, this works fine. As soon as they start using the search input as well, they can still end up in situations with 0 matches. We can prevent that by running a presearch of `${query} ${tag}` for each visible tag, but that impacts performance quite drastically.
Using the presearch would look like the snippet below. But when I implemented that, I noticed a serious delay while using the search input. Posting it here regardless, because maybe someone comes across it and have an idea on how to optimize it.
```js
const visibleTags = React.useMemo(() => {
if (!isSearching) {
return new Set(data.tags)
}
return new Set(
matchingPosts
.flatMap(post => post.frontmatter.categories)
// fake a search on current query + tag to …
```
> feat: disable filter buttons that would result in no matches

- app/routes/talks.tsx
Added a missing caption so that the filter has the same visual appearance as on `/blog`.
> feat: add caption above talks filter

- app/routes/blog/$slug.tsx
I've forced the aspect ratio to 3/4 (vertical) on small screen and 3/2 (horizontal) on medium and up.
fixes #69
> feat: force aspect ratio on blog banner images

- app/components/sections/featured-section.tsx
As mentioned in https://github.com/kentcdodds/remix-kentcdodds/projects/1#card-65512571
I've used the absolute child to stretch the link instead of wrapping everything in a link, so that the link doesn't interfere with the `copy link to clipboard` button.
> feat: make featured card clickable

- app/components/arrow-button.tsx
- app/components/button.tsx
- app/components/clipboard-copy-button.tsx
- app/components/footer.tsx
- app/routes/blog/$slug.tsx
- app/routes/chats.$season.$episode.$slug.tsx
- app/routes/chats.tsx
- app/routes/chats/$season.tsx
- styles/app.css
- styles/tailwind.css
- tailwind.config.js
I've run through all the pages, and fixed a bunch of focus styles. There are still a few things showing the native outline, but for those, I need a bit more inspiration.
I'm also working on a workaround for https://github.com/framer/motion/issues/1221. This PR already highlights at least the circle of arrow buttons, but it would be nice if the arrow moved as well, (also on <kbd>enter</kbd>). Got something working, and will submit it soon via dedicated PR for you to review.
> fix: improve various focus styles

- app/components/notification-message.tsx
Added a component that can be used to show notification messages. Note, that I have not added it to any pages! 
It's based on [`QueryParamNotificationMessage`](https://github.com/kentcdodds/kentcdodds.com/blob/f0e79f337096d0cd695643d292b5e425ca7d0c9d/src/components/notification-message.js#L90-L116) from the current site, with a few changes:
- the message can be rendered in two positions `top-center` and `bottom-right` (default).
- the message can get `autoClose={false}` as argument, so that the user must close it explicitly
- messages are shown one second after page load, to catch that extra bit of attention
My thoughts, render app notifications like `subscribed | form saved` etc `bottom-right` with default settings. And promotional messages like `epic discount!` in `top-center` with …
> feat: add component to show notification messages

- app/components/team-stats.tsx
Link still needs to point to some page.
Alternative ideas, instead of the text we could render a [`(?)`](https://iconic.app/help-circle/) or [`(i)`](https://iconic.app/information/) svg. Maybe a bit more subtle.
https://user-images.githubusercontent.com/1196524/127175550-a8e78b82-636e-4a75-bb75-874e78bec634.mp4
> feat: add 'help link' to team stats

- app/routes/chats.$season.$episode.$slug.tsx
- styles/app.css
I'm not sure why the designs show the "resource" links in a larger font size than "homework", making these the same size definitely looks better.
I've also reduced the size of spacings in the homework & resource sections, and styled the links in homework to have a different color than the text, and show an underline on focus&hover.
> feat: style homework links, reduce spacing, sync font-size

- app/routes/talks.tsx
- place the tag below the title on small screen
- render only a single column on medium screen
- prevent tag from growing in height due to line-wrapping in date
> feat: improve /talks for small & medium screen sizes

- styles/app.css
Make sure that non of the 'underlined' links get outlines on focus. This fixes the discord link in `/me`.
> feat: remove focus outline from underlined links

- styles/app.css
On android, the browser shows a light-blueish overlay on the tapped element. As all our elements do something on focus or tap, we already have something better. This removes the native style, a lot like removing the native focus outline.
> feat: remove tap highlight for touch devices

- app/routes/call.record.tsx
- app/routes/call.record/$callId.tsx
- use a background color instead of outline on accordion
- use the hover styles instead of outline on the `delete` button
> feat: improve focus styles call recorder

- app/routes/call.tsx
- app/routes/chats.tsx
Fixed the hover and focus style of the sort buttons on the `/chat` and `/call` pages, by adding a background color.
> feat: add focus style to sort chat/call buttons
